// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC93GznxkpDYYXTDzAo7ogOFDBVOmYUork',
    appId: '1:857958524723:web:2804a334cee1a6b3fdc046',
    messagingSenderId: '857958524723',
    projectId: 'hey-chat-f4701',
    authDomain: 'hey-chat-f4701.firebaseapp.com',
    storageBucket: 'hey-chat-f4701.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6xUDNfwu4ZL5nLxXQmqQHfB06k6Q8fA',
    appId: '1:857958524723:android:46cf16b021a29f4efdc046',
    messagingSenderId: '857958524723',
    projectId: 'hey-chat-f4701',
    storageBucket: 'hey-chat-f4701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Vp5b8atypmhtbDTNEBTlF2rluS6Brks',
    appId: '1:857958524723:ios:6bc82eea5e2d9885fdc046',
    messagingSenderId: '857958524723',
    projectId: 'hey-chat-f4701',
    storageBucket: 'hey-chat-f4701.firebasestorage.app',
    iosBundleId: 'com.example.hiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Vp5b8atypmhtbDTNEBTlF2rluS6Brks',
    appId: '1:857958524723:ios:6bc82eea5e2d9885fdc046',
    messagingSenderId: '857958524723',
    projectId: 'hey-chat-f4701',
    storageBucket: 'hey-chat-f4701.firebasestorage.app',
    iosBundleId: 'com.example.hiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC93GznxkpDYYXTDzAo7ogOFDBVOmYUork',
    appId: '1:857958524723:web:737cc4a16c6dbe96fdc046',
    messagingSenderId: '857958524723',
    projectId: 'hey-chat-f4701',
    authDomain: 'hey-chat-f4701.firebaseapp.com',
    storageBucket: 'hey-chat-f4701.firebasestorage.app',
  );
}
